// fixit-app/src/app/components/header/header.component.ts
import {AfterViewInit, ChangeDetectorRef, Component} from '@angular/core';
import {CommonModule} from '@angular/common';

@Component({
  selector: 'app-header',
  imports: [CommonModule],
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss'
})
export class HeaderComponent implements AfterViewInit {

  pages: any[] = [
    {id: "map", name: "Map"},
    {id: "about", name: "About us"},
    {id: "register", name: "Register"}
  ];
  ngAfterViewInit(): void {
  }

  headerHoverStart() {
    document.getElementById("header")?.classList.add('header-extended');
  }

  headerHoverEnd() {
    document.getElementById("header")?.classList.remove('header-extended');
  }
}

<div id="header" (mouseleave)="headerHoverEnd()">
  <div class="identity">
    <div class="logo">
      <img src="assets/images/fixit-logo1.png" height="60" width="60" alt=""/>
    </div>
    <div class="company">
      FixIt Augsburg
    </div>
  </div>
  <div class="extend-button" (mouseenter)="headerHoverStart()">
    >
  </div>
  <div class="title-container" *ngFor="let page of pages">
    {{page.name}}
  </div>
</div>

// fixit-app/src/components/header/header.tsx
import React, { useEffect } from 'react';
import { useLocation, Link } from 'react-router-dom';
import './header.scss'; // Assuming you have similar styles

const Header: React.FC = () => {
    const location = useLocation();

    const pages = [
        { id: "map", name: "Map" },
        { id: "about", name: "About us" },
        { id: "register", name: "Register" }
    ];

    useEffect(() => {
        console.log(location.pathname);
        if (!(location.pathname === "/map" || location.pathname === "/")) {
            headerHoverStart();
        }
    }, [location.pathname]);

    const headerHoverStart = () => {
        document.getElementById("header")?.classList.add("header-extended");
        document.documentElement.style.setProperty("--header-width", "100vw");
    };

    const headerHoverEnd = () => {
        if (location.pathname === "/map" || location.pathname === "/") {
            document.getElementById("header")?.classList.remove("header-extended");
            const detailVisible = document.getElementsByClassName("show-details")?.length > 0;
            document.documentElement.style.setProperty("--header-width", detailVisible ? "800px" : "400px");
        }
    };

    return (
        <div id="header" onMouseEnter={headerHoverStart} onMouseLeave={headerHoverEnd}>
            <div className="identity">
                <div className="logo">
                    <img src="/fixit-logo1.png" height="60" width="60" alt="" />
                </div>
                <div className="company">FixIt Augsburg</div>
            </div>
            <div className="extend-button">&gt;</div>
            <div className="title-wrapper">
                {pages.map((page) => (
                    <div className="title-container" key={page.id}>
                        <Link to={`/${page.id}`}>{page.name}</Link>
                    </div>
                ))}
            </div>
        </div>
    );
};

export default Header;
