// fixit-app/src/app/pages/map/map.component.ts
import {Component, AfterViewInit, HostListener} from '@angular/core';
import * as L from 'leaflet';
import {CommonModule} from '@angular/common';
import {repaircafes} from '../../../assets/data/repaircafes';

@Component({
  selector: 'app-map',
  imports: [CommonModule],
  templateUrl: './map.component.html',
  styleUrl: './map.component.scss'
})
export class MapComponent implements AfterViewInit {
  private map: any;

  //importiert die repaircafes aus den assets
  cafes: any[] = repaircafes;
  //wird automatisch ausgeführt nachdem die ansicht geladen ist
  ngAfterViewInit(): void {
    //initialisert die Karte und Marker für alle Cafes
    this.initMap();
    this.initMarkers();
  }

  @HostListener('document:keyup.escape', ['$event'])
  onEscapePressed(event: KeyboardEvent) {
    //simuliere klick auf map, um detailansicht zu schließen
    this.map.fireEvent('click');
  }

  //öffnet oder schließt das Cafe Detail Fenster
  toggleCafeDetails(cafe: any) {
    //click auf Element bereits im Fokus? -> schließt das Detail Fenster
    if(document.getElementById(cafe.id)?.classList.contains("list-element-focus")){
      this.closeCafeDetails();
      return;
    }

    //entfernt fokus von allen elementen mit fokus
    const oldFocusElements = document.getElementsByClassName("list-element-focus");
    for(let oldFocusElement of oldFocusElements) {
      oldFocusElement.classList.remove("list-element-focus");
    }

    //highlighted den Marker des geklickten Cafes
    this.highlightMarker(cafe.marker);

    //gibt dem geklickten element fokus
    const cafeListElement = document.getElementById(cafe.id);
    cafeListElement?.classList.add("list-element-focus");

    //wenn detail fenster schon offen, keine Änderungen
    if(document.getElementsByClassName("show-details").length === 0){ //sonst
      //setzt die Breite des headers auf 800px (liste + details)
      document.documentElement.style.setProperty(`--header-width`, "800px");
      //fügt das detail fenster hinzu
      document.getElementById("details")?.classList.add("show-details");
    }
  }

  //schließt das Cafe Detail Fenster
  closeCafeDetails() {
    //entfernt den Fokus von allen Elementen mit Fokus
    const focusElements = document.getElementsByClassName("list-element-focus");
    for(let focusElement of focusElements) {
      focusElement.classList.remove("list-element-focus");
    }

    //setzt die Breite des headers auf 400px (nur noch liste)
    document.documentElement.style.setProperty(`--header-width`, "400px");
    //entfernt das detail fenster
    document.getElementById("details")?.classList.remove("show-details");
  }

  //hovert über einen marker auf der map
  hoverStartCafeMarker(cafe: any) {
    //gibt der Liste den hover effect
    const cafeListElement = document.getElementById(cafe.id);
    cafeListElement?.classList.add("list-element-hover");

    //scrollt zum element in der liste
    cafeListElement?.scrollIntoView({ behavior: 'smooth', block: 'center' });

    //highlited den cafe marker auf der map
    this.highlightMarker(cafe.marker);
  }

  //hovert über ein cafe in der liste
  hoverStartCafeList(cafe: any) {
    this.highlightMarker(cafe.marker);
  }

  //highlight auf den marker
  private highlightMarker(cafeMarker: any) {
    //gibt es ein fokus element? wenn ja bezug auf dieses
    const focusElements = document.getElementsByClassName("list-element-focus");
    //jeder cafe marker
    this.cafes.forEach(cafe => {
      //wenn nicht der marker im fokus
      if(focusElements[0]?.id != cafe.id){
        //in den hintergrund, durchsichtig und ohne tooltip
        cafe.marker.setOpacity(0.2).setZIndexOffset(0).closeTooltip();
      }
    });
    //der gehoverte marker voll sichtbar in den vordergrund mit tooltip
    cafeMarker.setOpacity(1).setZIndexOffset(999).openTooltip();
  }
  //ende vom hover
  hoverEndCafe(cafe: any) {
    //entfernt alle hover css klassen
    const oldHoverElements = document.getElementsByClassName("list-element-hover");
    for(let oldHoverElement of oldHoverElements) {
      oldHoverElement.classList.remove("list-element-hover");
    }
    //wenn marker im fokus ist, highlight auch nach ende des hovers
    if(document.getElementById(cafe.id)?.classList.contains("list-element-focus")){
      this.highlightMarker(cafe.marker);
      return;
    }

    //wenn es ein element im fokus gibt
    const focusElements = document.getElementsByClassName("list-element-focus");
    if(focusElements.length > 0){
      //wieder zu diesem in der Liste scrollen
      focusElements[0].scrollIntoView({ behavior: 'smooth', block: 'center' });
      //den nicht mehr gehoverten marker wieder vernachlössigen
      cafe.marker.setOpacity(0.2).setZIndexOffset(0).closeTooltip();
      return;
    }
    //alle marker wieder auf standard
    this.removeHighlightMarker(cafe.marker);
  }

  //alle marker zurücksetzen
  private removeHighlightMarker(cafeMarker: any) {
    this.cafes.forEach(cafe => {
      cafe.marker.setOpacity(1);
    });
    cafeMarker.setZIndexOffset(0).closeTooltip();
  }

  //initialisierung der map
  private initMap(): void {
    this.map = L.map('map', {
      center: [ 48.354, 10.9 ],
      zoom: 14,
      zoomControl: false
    });

    L.control.zoom({
      position: 'bottomright'
    }).addTo(this.map);

    //map click listener
    this.map.on('click', () => {
      //entfernt detail ansicht
      this.closeCafeDetails();
      this.cafes.forEach(cafe => {
        cafe.marker.setOpacity(1);
      });
    });

    //lädt karten daten
    const tiles = L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png', {
      maxZoom: 19,
      minZoom: 11});
    tiles.addTo(this.map);
  }

  //initialisiert karten cafe marker
  private initMarkers(): void {
    //definiert das marker icon
    const customMarkerIcon = L.icon({
      iconUrl: 'assets/images/marker.png',  // Pfad zum benutzerdefinierten Bild
      className: 'custom-marker',
      iconSize: [40, 40],   // Größe des Icons
      iconAnchor: [20, 40], // Der Punkt im Icon, der mit der Position des Markers auf der Karte übereinstimmt
      popupAnchor: [0, -40] // Der Abstand des Popups relativ zum Marker
    });

    //für jedes cafe ein marker
    this.cafes.forEach(cafe => {
      if (cafe.lat !== undefined && cafe.lng !== undefined) {
        const customTooltip = L.tooltip({
          className: 'custom-tooltip', //css Klasse
          direction: 'bottom', // Richtung des Tooltips
          offset: [0, -5] //offset x,y
        }).setContent(cafe.name);
        //fügt den marker hinzu
        cafe['marker'] = L.marker([cafe?.lat, cafe?.lng], { icon: customMarkerIcon, riseOnHover: true }).addTo(this.map).bindTooltip(customTooltip);

        //listener maus drüber (hover start)
        cafe['marker'].on('mouseover', () => {
          this.hoverStartCafeMarker(cafe);
        });

        //listener maus weg (hover ende)
        cafe['marker'].on('mouseout', () => {
          this.hoverEndCafe(cafe);
        });

        //listener mouse klick
        cafe['marker'].on('click', () => {
          this.toggleCafeDetails(cafe);
        });
      }
    });
  }
}

<div class="wrapper">
  <div class="list">
    <div [id]="cafe.id" class="list-element" *ngFor="let cafe of cafes" (click)="toggleCafeDetails(cafe)" (mouseenter)="hoverStartCafeList(cafe)" (mouseleave)="hoverEndCafe(cafe, true)">
      <div class="list-element-name">
        {{cafe.name}}
      </div>
      <div class="list-element-description">
        {{cafe.description}}
      </div>
      <div class="list-element-type">
        {{cafe.type}}
      </div>
    </div>
  </div>
  <div id="details">

  </div>
  <div id="map-frame">
    <div id="map"></div>
  </div>
</div>

// fixit-app/src/pages/map/map.tsx
import React, { useEffect, useRef, useState, KeyboardEvent } from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import repaircafes from '../../assets/repaircafes.json';
import './map.scss';  // Adjust the path as necessary
import { MapContainer, TileLayer, Marker, Tooltip, ZoomControl } from 'react-leaflet'



interface Cafe {
    id: string;
    name: string;
    description: string;
    type: string;
    lat?: number;
    lng?: number;
    marker?: any;
}

const Map: React.FC = () => {
    const [cafes, setCafes] = useState<Cafe[]>([]);
    const mapRef = useRef<any>(null);
    const markerIcon = L.icon({
        iconUrl: '/marker.png',
        className: 'custom-marker',
        iconSize: [40, 40],
        iconAnchor: [20, 40],
        popupAnchor: [0, -40]
    });

    useEffect(() => {
        setCafes(repaircafes);

        if(mapRef.current) {
            mapRef.current.on('click', () => {
                closeCafeDetails();
                cafes.forEach(cafe => {
                    cafe.marker?.setOpacity(1);
                });
            });
        }
    }, []);


    const toggleCafeDetails = (cafe: Cafe) => {
        const el = document.getElementById(cafe.id);
        if (el?.classList.contains('list-element-focus')) {
            closeCafeDetails();
            return;
        }

        document.querySelectorAll('.list-element-focus').forEach(el =>
            el.classList.remove('list-element-focus')
        );

        highlightMarker(cafe.marker);
        el?.classList.add('list-element-focus');

        if (document.querySelectorAll('.show-details').length === 0) {
            document.documentElement.style.setProperty('--header-width', '800px');
            document.getElementById('details')?.classList.add('show-details');
        }
    };

    const closeCafeDetails = () => {
        document.querySelectorAll('.list-element-focus').forEach(el =>
            el.classList.remove('list-element-focus')
        );
        document.documentElement.style.setProperty('--header-width', '400px');
        document.getElementById('details')?.classList.remove('show-details');
    };

    const hoverStartCafeMarker = (cafe: Cafe) => {
        const el = document.getElementById(cafe.id);
        el?.classList.add('list-element-hover');
        el?.scrollIntoView({ behavior: 'smooth', block: 'center' });
        highlightMarker(cafe.marker);
    };

    const hoverStartCafeList = (cafe: Cafe) => {
        highlightMarker(cafe.marker);
    };

    const highlightMarker = (marker: any) => {
        const focused = document.querySelector('.list-element-focus')?.id;
        cafes.forEach(c => {
            if (c.id !== focused) {
                c.marker?.setOpacity(0.2).setZIndexOffset(0).closeTooltip();
            }
        });
        marker?.setOpacity(1).setZIndexOffset(999).openTooltip();
    };

    const hoverEndCafe = (cafe: Cafe, triggerByListElement: boolean = false) => {
        document.querySelectorAll('.list-element-hover').forEach(el =>
            el.classList.remove('list-element-hover')
        );

        const isFocused = document.getElementById(cafe.id)?.classList.contains('list-element-focus');
        if (isFocused) {
            highlightMarker(cafe.marker);
            return;
        }

        const focusEl = document.querySelector('.list-element-focus') as HTMLElement;
        if (focusEl) {
            if(!triggerByListElement){
                focusEl.scrollIntoView({ behavior: 'smooth', block: 'center' });
            }
            cafe.marker?.setOpacity(0.2).setZIndexOffset(0).closeTooltip();
        } else {
            cafes.forEach(c => c.marker?.setOpacity(1));
            cafe.marker?.setZIndexOffset(0).closeTooltip();
        }
    };

    return (
        <div className="wrapper">
            <div className="list">
                {cafes.map((cafe) => (
                    <div
                        id={cafe.id}
                        key={cafe.id}
                        className="list-element"
                        onClick={() => toggleCafeDetails(cafe)}
                        onMouseEnter={() => hoverStartCafeList(cafe)}
                        onMouseLeave={() => hoverEndCafe(cafe, true)}
                    >
                        <div className="list-element-name">{cafe.name}</div>
                        <div className="list-element-description">{cafe.description}</div>
                        <div className="list-element-type">{cafe.type}</div>
                    </div>
                ))}
            </div>
            <div id="details"></div>
            <div id="map-frame">
                <MapContainer id={"map"} center={[48.354, 10.9]} zoom={14} zoomControl={false}>
                    <TileLayer
                        url="https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png"
                        maxZoom={19} minZoom={11}
                    />
                    <ZoomControl position="bottomright" />
                    {cafes.map((cafe) => (
                        <Marker
                            key={cafe.id}
                            position={[cafe.lat!, cafe.lng!]}
                            icon={markerIcon}
                            eventHandlers={{
                                click: () => toggleCafeDetails(cafe), // Add click handler here
                                mouseover: () => hoverStartCafeMarker(cafe), // Add click handler here
                                mouseout: () => hoverEndCafe(cafe), // Add click handler here
                            }}>
                            <Tooltip
                                className={"custom-tooltip"}
                                offset={[0, -5]}
                                direction={"bottom"}>
                                {cafe.name}
                            </Tooltip>
                        </Marker>
                    ))}
                </MapContainer>
            </div>
        </div>
    );
};

export default Map;
